FROM httpd:2.4

EXPOSE 443

RUN sed -i \
      -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
      -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
      -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
      conf/httpd.conf

COPY ./ssl/ /usr/local/apache2/conf/
COPY ./index.html /usr/local/apache2/htdocs/